services:
  bedrock:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/var/www/html:cached
    ports:
      - ${APP_PORT:-80}:80
    environment:
      - APP_ENV=${APP_ENV:-development}
      - APP_DEBUG=${APP_DEBUG:-true}
      - APP_DOMAIN=${APP_DOMAIN:-localhost}
      - DB_HOST=db
      - DB_NAME=${DB_NAME:-bedrock}
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - WP_ENV=${APP_ENV:-development}
      - WP_HOME=http://${APP_DOMAIN:-localhost}
      - WP_SITEURL=http://${APP_DOMAIN:-localhost}/wp
      - AUTH_KEY=${AUTH_KEY}
      - SECURE_AUTH_KEY=${SECURE_AUTH_KEY}
      - LOGGED_IN_KEY=${LOGGED_IN_KEY}
      - NONCE_KEY=${NONCE_KEY}
      - AUTH_SALT=${AUTH_SALT}
      - SECURE_AUTH_SALT=${SECURE_AUTH_SALT}
      - LOGGED_IN_SALT=${LOGGED_IN_SALT}
      - NONCE_SALT=${NONCE_SALT}
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME:-bedrock}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-root}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"

volumes:
  db_data:
