services:
  bedrock:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html:rw
      - uploads:/var/www/html/web/app/uploads:rw  # Switch back to named volume
    env_file:
      - .env.salts
    environment:
      APP_ENV: ${APP_ENV:-development}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:8080}

      WP_ENV: ${APP_ENV:-development}
      WP_HOME: ${APP_URL:-http://localhost:8080}
      WP_SITEURL: ${APP_URL:-http://localhost:8080}/wp

      DB_NAME: ${DB_NAME:-bedrock}
      DB_USER: ${DB_USER:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      DB_HOST: db
    restart: always

  db:
    image: mariadb:latest
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME:-bedrock}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
    restart: always

  nginx:
    image: nginx:latest
    depends_on:
      - bedrock
    ports:
      - "80:80"  # Changed from 8080 to 80 for proper domain handling
    environment:
      - APP_DOMAIN=${APP_DOMAIN:-localhost}
    command: /bin/bash -c "envsubst '$$APP_DOMAIN' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf.template:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - .:/var/www/html:rw
      - uploads:/var/www/html/web/app/uploads:rw  # Add uploads volume to nginx
    restart: always

volumes:
  database:
  uploads:
